<a href="https://colab.research.google.com/github/Meriem-BERRAHOU/Machine-learning-Projects/blob/simple-projects/Spam_mail.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer

In [5]:
mail_data = pd.read_csv('/content/mail_data.csv')
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
mail_data.shape

(5572, 2)

In [7]:
mail_data.describe()

       Category                 Message
count      5572                    5572
unique        2                    5157
top         ham  Sorry, I'll call later
freq       4825                      30

In [8]:
mail_data.isnull().sum()

Category    0
Message     0
dtype: int64

In [12]:
mail_data.replace({'Category':{'ham':0,'spam':1}},inplace=True)
mail_data.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

Split data

In [37]:
X= mail_data.drop(['Category'],axis=1)
Y= mail_data['Category']

In [38]:
print(X)

                                                Message
0     Go until jurong point, crazy.. Available only ...
1                         Ok lar... Joking wif u oni...
2     Free entry in 2 a wkly comp to win FA Cup fina...
3     U dun say so early hor... U c already then say...
4     Nah I don't think he goes to usf, he lives aro...
...                                                 ...
5567  This is the 2nd time we have tried 2 contact u...
5568               Will ü b going to esplanade fr home?
5569  Pity, * was in mood for that. So...any other s...
5570  The guy did some bitching but I acted like i'd...
5571                         Rofl. Its true to its name

[5572 rows x 1 columns]

In [30]:
print(Y)

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: Category, Length: 5572, dtype: int64

data text-->int64

In [39]:
#vicotorization of message
vectorizer = TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)
X_values=X['Message'].values
X=vectorizer.fit_transform(X_values)
print(X.shape)

(5572, 8440)

In [40]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 43529 stored elements and shape (5572, 8440)>
  Coords	Values
  (0, 4244)	0.35097479377088364
  (0, 5775)	0.27451666535585145
  (0, 2278)	0.27180581777101714
  (0, 1281)	0.26251769953088055
  (0, 1715)	0.29650492406235857
  (0, 3551)	0.19387866945820545
  (0, 8281)	0.23740715800944148
  (0, 4370)	0.29650492406235857
  (0, 1713)	0.3350433781715565
  (0, 2003)	0.29650492406235857
  (0, 3511)	0.16453831818791093
  (0, 1061)	0.35097479377088364
  (0, 8079)	0.1961033223643189
  (1, 5373)	0.2718944069420321
  (1, 4406)	0.4083258549263009
  (1, 4212)	0.5236804332035243
  (1, 8187)	0.43162957585464123
  (1, 5399)	0.5466243141314314
  (2, 3276)	0.11676028650249681
  (2, 2885)	0.36440225960212075
  (2, 8239)	0.19287984407221892
  (2, 2119)	0.19686982823560253
  (2, 8199)	0.14953315491852773
  (2, 3014)	0.47550942852592687
  (2, 2337)	0.20418515380343544
  :	:
  (5567, 2777)	0.23210746089026935
  (5567, 307)	0.24294734175129457
  (5567, 707)	0.24981723092165423
  (5567, 5836)	0.2799050574582319
  (5567, 165)	0.33657880027391784
  (5567, 5293)	0.33657880027391784
  (5568, 3809)	0.3652059777476414
  (5568, 3480)	0.3642369776828009
  (5568, 3263)	0.5597098620657655
  (5568, 2917)	0.6485991737677518
  (5569, 5018)	0.5068968918274174
  (5569, 5707)	0.6095307789831879
  (5569, 7213)	0.6095307789831879
  (5570, 3276)	0.19998200231369734
  (5570, 8125)	0.23564264513684635
  (5570, 4508)	0.19998200231369734
  (5570, 2542)	0.23105123281877282
  (5570, 3388)	0.3451679596114425
  (5570, 1749)	0.35475111861632075
  (5570, 3605)	0.30408849117263737
  (5570, 4063)	0.35475111861632075
  (5570, 908)	0.40721605986134385
  (5570, 1511)	0.42657930865550353
  (5571, 7705)	0.6048659564126764
  (5571, 6362)	0.7963273037972378

In [41]:
#split data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=3)
print(X.shape,X_train.shape,X_test.shape)

(5572, 8440) (4457, 8440) (1115, 8440)

Train data --->logistic regression

In [42]:
model = LogisticRegression()
model.fit(X_train,Y_train)

LogisticRegression()

Evaluation -->accuracy score

In [43]:
#train data accuracy score
train_pred = model.predict(X_train)
train_acc = accuracy_score(Y_train,train_pred)
print(train_acc)

0.9670181736594121

In [44]:
#train test accuracy score
test_pred = model.predict(X_test)
test_acc = accuracy_score(Y_test,test_pred)
print(test_acc)

0.9524663677130045

Build a predictive system

In [52]:
email_text="you win a reward with us of value $2000..call on 1234567890 to get it"
email_numerical=vectorizer.transform([email_text])
pred=model.predict(email_numerical)
if pred[0]==0:
  print("ham mail")
else:
  print("spam mail")

ham mail

In [51]:
X_test_exemple = X_test[1114]
pred = model.predict(X_test_exemple)
if pred[0]==0:
  print("ham mail")
else:
  print("spam mail")

ham mail